import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const read = file => readFile(path.join(root, file), 'utf8');
const json = async file => JSON.parse(await read(file));
const sha256 = content => createHash('sha256').update(content).digest('hex');
const save = async (file, content) => {
  const target = path.join(root, file);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, content);
};
const lock = await json('package-lock.json');
const bundled = await json('dist-pages/legal/bundled-dependencies.json');
const additions = await json('docs/legal/third-party-sources.json');
const accepted = new Set(['MIT', 'ISC', 'Apache-2.0', '0BSD', 'BSD-2-Clause', 'BSD-3-Clause']);
const selected = new Map();

for (const entry of bundled) {
  if (!entry.text?.trim()) throw new Error(`Missing bundled licence text: ${entry.name}`);
  selected.set(`${entry.name}@${entry.version}`, {
    name: entry.name, version: entry.version, scopes: ['Included in Vite’s production JavaScript inventory.'],
  });
}
for (const addition of additions) {
  const pkg = await json(`node_modules/${addition.name}/package.json`);
  const key = `${pkg.name}@${pkg.version}`;
  const entry = selected.get(key) ?? { name: pkg.name, version: pkg.version, scopes: [] };
  entry.scopes.push(addition.scope);
  selected.set(key, entry);
}
if (!selected.has(`react@${lock.packages['node_modules/react'].version}`)) {
  throw new Error('Production licence inventory is incomplete: React is missing.');
}

const packages = [];
let notices = 'Tumble Grove — third-party notices\n\n';
notices += 'Generated by npm run build from the locked production JavaScript inventory,\n';
notices += 'plus the CSS, adapted UI source and helpers in docs/legal/third-party-sources.json.\n';
notices += 'Each component retains its own permissions and conditions. These notices do not\n';
notices += 'license original Tumble Grove contributions or grant trademark/endorsement rights.\n';
notices += 'Some upstream licence files also include notices for their own bundled components.\n';

for (const entry of [...selected.values()].sort((a, b) => a.name.localeCompare(b.name, 'en') || a.version.localeCompare(b.version, 'en'))) {
  const match = Object.entries(lock.packages).find(([directory, pkg]) =>
    directory.endsWith(`node_modules/${entry.name}`) && pkg.version === entry.version);
  if (!match) throw new Error(`Package is absent from lockfile: ${entry.name}@${entry.version}`);
  const [directory] = match;
  const pkg = await json(`${directory}/package.json`);
  if (pkg.name !== entry.name || pkg.version !== entry.version) {
    throw new Error(`Installed package differs from lockfile: ${entry.name}`);
  }
  if (!accepted.has(pkg.license)) {
    throw new Error(`Review the licence before distribution: ${pkg.name} (${pkg.license ?? 'unknown'})`);
  }
  const files = (await readdir(path.join(root, directory), { withFileTypes: true }))
    .filter(file => file.isFile() && /^(licen[cs]e|copying|notice)(\.|$|-)/i.test(file.name))
    .map(file => file.name).sort();
  if (!files.some(file => /^(licen[cs]e|copying)/i.test(file))) {
    throw new Error(`Missing licence file: ${pkg.name}`);
  }
  const records = [];
  notices += `\n${'='.repeat(72)}\n${pkg.name} ${pkg.version} — ${pkg.license}\n`;
  notices += entry.scopes.join('\n') + '\n';
  for (const file of files) {
    const content = await read(`${directory}/${file}`);
    if (!content.trim()) throw new Error(`Empty notice: ${directory}/${file}`);
    records.push({ file, sha256: sha256(content) });
    notices += `\n--- ${file} ---\n${content}${content.endsWith('\n') ? '' : '\n'}`;
  }
  const repository = typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url;
  packages.push({ ...entry, license: pkg.license, repository: repository ?? null, noticeFiles: records });
}

const inventory = JSON.stringify({
  scope: 'Bundled JavaScript plus explicitly recorded styles, helpers and adapted component source. Not a legal clearance opinion.',
  packageLockSha256: sha256(await read('package-lock.json')),
  packages,
}, null, 2) + '\n';
const projectLicense = await read('LICENSE');
await save('THIRD_PARTY_NOTICES.txt', notices);
await save('docs/legal/dependency-inventory.json', inventory);
for (const directory of ['public/legal', 'dist-pages/legal']) {
  await save(`${directory}/third-party-notices.txt`, notices);
  await save(`${directory}/project-license.txt`, projectLicense);
  await save(`${directory}/dependency-inventory.json`, inventory);
}

const assets = [
  'public/fruits.png', 'public/artwork-prompt.txt',
  'public/fruit-collection-a.png', 'public/fruit-collection-a-prompt.txt',
  'public/fruit-collection-b.png', 'public/fruit-collection-b-prompt.txt',
  'public/favicon.svg', 'public/manifest.webmanifest',
  'app/fruit-shapes.ts', 'app/collection-shapes.ts', 'app/fruit-collection.ts',
  'scripts/trace-fruit-shapes.py', 'scripts/trace-collection.py',
  'docs/fruit-size-research.json', 'public/fruit-sizes.csv',
];
const hashes = [];
for (const file of assets) {
  const content = await readFile(path.join(root, file));
  hashes.push({ path: file, sha256: sha256(content), bytes: content.length });
}
await save('docs/legal/asset-hashes.json', JSON.stringify({
  note: 'Fingerprints identify the recorded files. They do not establish authorship, copyrightability or non-infringement.',
  files: hashes,
}, null, 2) + '\n');
console.log(`Legal records prepared: ${packages.length} packages; ${hashes.length} asset/source fingerprints.`);
