"""Measure body silhouettes in the existing PNG; emit geometry, never edit artwork.
Run only when the sprite sheet changes. Requires Pillow for PNG pixel inspection.
"""
import json, math
from pathlib import Path
from PIL import Image
ROOT = Path(__file__).resolve().parents[1]
im = Image.open(ROOT / 'public/fruits.png').convert('RGB')
crops = [[34,40,308,309],[426,37,266,313],[771,33,286,320],[1120,34,304,323],[29,386,310,300],[406,363,299,326],[768,365,291,326],[1124,385,288,292],[36,684,290,350],[397,719,300,320],[755,689,308,354]]
# The lower bounds isolate fruit flesh from decorative stems and leafy crowns.
body_top = [187,106,76,103,441,427,446,418,782,781,739]
def body_pixel(kind, x, y):
    r,g,b = im.getpixel((x,y))
    if y < body_top[kind] or min(r,g,b)>220: return False
    if kind in (0,1,5,7): return r > g*1.15 and r > b*1.08
    if kind == 2: return b > g*1.13 and r > g*1.03
    if kind in (3,4,8): return r > g*1.09 and g > b*1.18
    return max(r,g,b)-min(r,g,b)>27 and g > b*1.15

def cross(a,b,c): return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])
def hull(points):
    points=sorted(set(points)); low=[]; high=[]
    for p in points:
        while len(low)>1 and cross(low[-2],low[-1],p)<=0: low.pop()
        low.append(p)
    for p in reversed(points):
        while len(high)>1 and cross(high[-2],high[-1],p)<=0: high.pop()
        high.append(p)
    return low[:-1]+high[:-1]
def simplify(points):
    # Keep chords within 1.4 source pixels of the measured silhouette.
    while len(points)>12:
        errors=[]
        for i,p in enumerate(points):
            a,b=points[i-1],points[(i+1)%len(points)]
            errors.append(abs(cross(a,b,p))/max(.001,math.dist(a,b)))
        index=min(range(len(points)),key=lambda i:errors[i])
        if errors[index]>1.4 and len(points)<=24: break
        points.pop(index)
    return points

shapes=[]
for kind,(x,y,w,h) in enumerate(crops):
    boundary=[]
    for py in range(y,y+h):
        row=[px for px in range(x,x+w) if body_pixel(kind,px,py)]
        if len(row)>3: boundary.extend([(row[0],py),(row[-1],py)])
    outline=simplify(hull(boundary))
    x0=min(p[0] for p in outline);x1=max(p[0] for p in outline)
    y0=min(p[1] for p in outline);y1=max(p[1] for p in outline)
    cx=(x0+x1)/2;cy=(y0+y1)/2;radius=max(x1-x0,y1-y0)/2
    # A 0.35-pixel inset puts contact inside antialiasing rather than outside it.
    inset=1-.35/radius
    shapes.append(dict(crop=[x,y,w,h],center=[cx-x,cy-y],radius=radius,hull=[[round((px-cx)/radius*inset,5),round((py-cy)/radius*inset,5)] for px,py in outline]))
    print(kind,'body bounds', [x0,y0,x1,y1], 'hull vertices',len(outline))
header='// Generated by scripts/trace-fruit-shapes.py from public/fruits.png.\n// Coordinates share the same body-centered origin for rendering and physics.\n'
(ROOT/'app/fruit-shapes.ts').write_text(header+'export const FRUIT_SHAPES = '+json.dumps(shapes,separators=(',',':'))+' as const;\n')
