"""Read sprite pixels and measure crops/hulls; never modify the artwork."""
import json, math
from pathlib import Path
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
def cross(a,b,c):return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])
def hull(points):
    points=sorted(set(points));low=[];high=[]
    for p in points:
        while len(low)>1 and cross(low[-2],low[-1],p)<=0:low.pop()
        low.append(p)
    for p in reversed(points):
        while len(high)>1 and cross(high[-2],high[-1],p)<=0:high.pop()
        high.append(p)
    result=low[:-1]+high[:-1]
    while len(result)>16:
        errors=[abs(cross(result[i-1],result[(i+1)%len(result)],p))/max(.001,math.dist(result[i-1],result[(i+1)%len(result)])) for i,p in enumerate(result)]
        i=min(range(len(result)),key=lambda i:errors[i])
        if errors[i]>.7 and len(result)<=22:break
        result.pop(i)
    return result
sheets=[]
for sheet in ['a','b']:
    im=Image.open(ROOT/f'public/fruit-collection-{sheet}.png').convert('RGB');w,h=im.size
    def ink(x,y):
        r,g,b=im.getpixel((x,y));return min(r,g,b)<205 or max(r,g,b)-min(r,g,b)>32
    row_counts=[sum(ink(x,y) for x in range(w)) for y in range(h)]
    separators=[0]
    for row in range(1,11):
        middle=round(h*row/11);lo=round(middle-h/11*.22);hi=round(middle+h/11*.22)
        separators.append(min(range(lo,hi),key=lambda y:(sum(row_counts[max(0,y-2):y+3]),abs(y-middle))))
    separators.append(h)
    cells=[]
    for row in range(11):
        for col in range(5):
            left=round(w*col/5);right=round(w*(col+1)/5);top=separators[row];bottom=separators[row+1]
            pixels=[(x,y) for y in range(top,bottom) for x in range(left,right) if ink(x,y)]
            x0=min(x for x,y in pixels);x1=max(x for x,y in pixels);y0=min(y for x,y in pixels);y1=max(y for x,y in pixels)
            # Narrow stems and leafy protrusions are decorative. Start at the body shoulder.
            spans={y:[] for y in range(y0,y1+1)}
            for x,y in pixels:spans[y].append(x)
            widths={y:max(xs)-min(xs)+1 if xs else 0 for y,xs in spans.items()};max_width=max(widths.values())
            body_top=next(y for y in range(y0,y1+1) if sum(widths.get(k,0)>=max_width*.55 for k in range(y,y+5))>=4)
            center_sample=[im.getpixel((x,y)) for x,y in pixels if y>y0+(y1-y0)*.45 and y<y0+(y1-y0)*.7]
            avg=[sum(p[i] for p in center_sample)/len(center_sample) for i in range(3)]
            green_body=avg[1]>avg[0]*.92 and avg[1]>avg[2]*1.1
            body=[]
            for x,y in pixels:
                if y<body_top:continue
                r,g,b=im.getpixel((x,y))
                if not green_body and y<y0+(y1-y0)*.3 and g>r*1.05 and g>b*1.2:continue
                body.append((x,y))
            outline=hull(body);bx0=min(x for x,y in outline);bx1=max(x for x,y in outline);by0=min(y for x,y in outline);by1=max(y for x,y in outline)
            cx=(bx0+bx1)/2;cy=(by0+by1)/2;radius=max(bx1-bx0,by1-by0)/2
            # Crop preserves all decorative artwork and two pixels of antialiasing.
            x0=max(left,x0-2);x1=min(right-1,x1+2);y0=max(top,y0-2);y1=min(bottom-1,y1+2)
            inset=1-.22/radius
            cells.append(dict(sheet=f'fruit-collection-{sheet}.png',crop=[x0,y0,x1-x0+1,y1-y0+1],center=[cx-x0,cy-y0],radius=radius,hull=[[round((x-cx)/radius*inset,5),round((y-cy)/radius*inset,5)] for x,y in outline]))
    sheets.append(cells)
    print(sheet,'rows',separators,'characters',len(cells),'minimum radius',min(s['radius'] for s in cells))
selected=[]
for row in range(11):selected.extend(sheets[0][row*5+1:row*5+5]+sheets[1][row*5:row*5+5])
(ROOT/'app/collection-shapes.ts').write_text('// Generated by scripts/trace-collection.py; body-centered artwork geometry.\nexport const COLLECTION_SHAPES = '+json.dumps(selected,separators=(',',':'))+' as const;\n')
